language: swift
osx_image: xcode10
xcode_project: Static.xcodeproj

script: xcodebuild -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$TRAVIS_XCODE_SDK" -destination "$DESTINATION" test

matrix:
  include:
    - xcode_scheme: Static-iOS
      xcode_sdk: iphonesimulator
      env:
        - DESTINATION="OS=10.1,name=iPhone 7 Plus"
